excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://chaque.co
title: Chaque
email: hello@chaque.co
author: Chaque
description: My personal blog
paginate: 5
google_analytics: 
